networks:
  away-zone:
    name: away-zone

services:
  web:
    image: away-zone-web:${DOCKERFILE_TARGET}
    pull_policy: build
    build:
      context: ./src/web
      dockerfile: ../../Dockerfile
      target: builder
      args:
        - EXECUTABLE_NAME=web-app
    ports:
      - "8000:8000"
    container_name: web
    restart: unless-stopped
    networks:
      - away-zone

  health-checker:
    image: away-zone-health-checker:${DOCKERFILE_TARGET}
    pull_policy: build
    build:
      context: src/health-checker
      dockerfile: ../../Dockerfile
      target: builder
      # target: ${DOCKERFILE_TARGET}
      args:
        - EXECUTABLE_NAME=health-checker
    container_name: health-checker
    restart: unless-stopped
    networks:
      - away-zone
