networks:
  away-zone:
    name: away-zone

services:
  web:
    image: away-zone-web:${IMAGE_TAG:-latest}
    pull_policy: build
    build:
      context: apps/web
      dockerfile: ../../Dockerfile
      target: web
      args:
        - EXECUTABLE_NAME=web-app
    ports:
      - "8000:8000"
    container_name: web
    restart: unless-stopped
    networks:
      - away-zone

  health-checker:
    image: away-zone-health-checker:${IMAGE_TAG:-latest}
    pull_policy: build
    build:
      context: apps/health-checker
      dockerfile: ../../Dockerfile
      target: health-checker
      args:
        - EXECUTABLE_NAME=health-checker
    container_name: health-checker
    restart: unless-stopped
    networks:
      - away-zone
